# Generated by Django 3.2.9 on 2025-04-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('pharmacy_owner', 'Pharmacy Owner'), ('pharmacist_admin', 'Pharmacist Admin'), ('pharmacist', 'Pharmacist'), ('user', 'User'), ('super_admin', 'Super Admin')], default='pharmacist', max_length=35),
        ),
    ]
